# Automatisch erzeugt von Werkzeuge/sprachen.py - nicht von Hand bearbeiten.
# Arabische Texte sind bereits in Anzeigeform (verbunden, rechts-nach-links).
module SR
  # Zeichen, die die Spielschrift »Power Green« enthält (alles andere -> SR Unifont)
  FONT_OK = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿŒœΔΚΜΠΡδ‘’“”•…№①②③④⑤⑥⑦⑧⑨■□▲△▴▶▸▼▾◀◂○◎●★☢☽☾♀♂♈♌♐♒♠♣♥♦♩♪♫✨❶❷❸❹❺❻❼❽❾".chars.to_h { |c| [c, true] }
  LANG_ORDER = [:es, :ar, :fr, :en, :tr, :uk]
  ORIGINS = {
   :es => {
      :label => "Spanisch",
      :native => "Español",
      :first => "Daniela",
      :last => "Ríos",
      :city => "Medellín",
      :land => "Kolumbien",
      :aus => "aus Kolumbien",
      :inn => "in Kolumbien",
      :staat => "kolumbianisch",
      :pass_head => "República de Colombia - Pasaporte",
      :uni => "Universidad de Antioquia, Medellín",
      :heimweh => "Ich vermisse Mamas Arepas. Und die Sonne.",
      :buch => "ein Roman von García Márquez",
      :zeit => "In Medellín ist es jetzt sieben Stunden früher.",
      :name_ok => "sogar mit Akzent!",
      :endlich => "Por fin.",
      :mama1 => "¿Mija? ¿Cómo estás? ¿Ya llegaste?",
      :ja_mama => "Sí, mamá.",
      :alles_gut => "Todo bien.",
      :mama2 => "¿Y la gente? ¿Son amables?",
      :schritt => "Paso a paso",
      :toll => "¡Qué bien!",
      :musiker_her => "Valparaíso, Chile",
      :musiker_aus => "aus Chile",
      :tarek => "¿Español? Un poquito. Ich war ein Jahr in Valencia.",
      :jonas => "Ich kann nur »una cerveza, por favor«."
   },
   :ar => {
      :label => "Arabisch",
      :native => "ﺔﻴﺑﺮﻌﻟﺍ",
      :first => "Rania",
      :last => "Haddad",
      :city => "Amman",
      :land => "Jordanien",
      :aus => "aus Jordanien",
      :inn => "in Jordanien",
      :staat => "jordanisch",
      :pass_head => "Hashemite Kingdom of Jordan - Passport",
      :uni => "Universität von Jordanien, Amman",
      :heimweh => "Ich vermisse Mamas Mansaf. Und die Sonne.",
      :buch => "Gedichte von Mahmud Darwisch",
      :zeit => "In Amman ist es jetzt eine Stunde später.",
      :name_ok => "richtig geschrieben!",
      :endlich => ".ﺍﺮﻴﺧﺃ",
      :mama1 => "؟ﻚﻟﺎﺣ ﻒﻴﻛ ،ﻲﺘﺒﻴﺒﺣ",
      :ja_mama => ".ﺎﻣﺎﻣ ﺎﻳ ﻢﻌﻧ",
      :alles_gut => ".ﺮﻴﺨﺑ ﺀﻲﺷ ﻞﻛ",
      :mama2 => "؟ﺀﺎﻔﻄﻟ ﻢﻫ ﻞﻫ ؟ﺱﺎﻨﻟﺍﻭ",
      :schritt => "ﺓﻮﻄﺧ ﺓﻮﻄﺧ",
      :toll => "!ﻡﻼﺳ ﺎﻳ",
      :musiker_her => "Beirut, Libanon",
      :musiker_aus => "aus dem Libanon",
      :tarek => "Shwayy - ein bisschen! Meine Eltern kommen aus dem Libanon.",
      :jonas => "Ich kann nur »Schukran«."
   },
   :fr => {
      :label => "Französisch",
      :native => "Français",
      :first => "Aminata",
      :last => "Diallo",
      :city => "Dakar",
      :land => "Senegal",
      :aus => "aus dem Senegal",
      :inn => "im Senegal",
      :staat => "senegalesisch",
      :pass_head => "République du Sénégal - Passeport",
      :uni => "Université Cheikh Anta Diop, Dakar",
      :heimweh => "Ich vermisse Mamas Thieboudienne. Und das Meer.",
      :buch => "ein Roman von Mariama Bâ",
      :zeit => "In Dakar ist es jetzt zwei Stunden früher.",
      :name_ok => "richtig geschrieben!",
      :endlich => "Enfin.",
      :mama1 => "Ma chérie, ça va ? Tu es arrivée ?",
      :ja_mama => "Oui, maman.",
      :alles_gut => "Tout va bien.",
      :mama2 => "Et les gens ? Ils sont gentils ?",
      :schritt => "Pas à pas",
      :toll => "Super !",
      :musiker_her => "Montréal, Kanada",
      :musiker_aus => "aus Kanada",
      :tarek => "Un peu. Französisch hatte ich in der Schule. Lange her!",
      :jonas => "Ich kann nur »un croissant, s'il vous plaît«."
   },
   :en => {
      :label => "Englisch",
      :native => "English",
      :first => "Joy",
      :last => "Santos",
      :city => "Manila",
      :land => "Philippinen",
      :aus => "von den Philippinen",
      :inn => "auf den Philippinen",
      :staat => "philippinisch",
      :pass_head => "Republic of the Philippines - Passport",
      :uni => "University of the Philippines, Manila",
      :heimweh => "Ich vermisse Mamas Adobo. Und die Sonne.",
      :buch => "ein Roman von Nick Joaquín",
      :zeit => "In Manila ist es jetzt sechs Stunden später.",
      :name_ok => "richtig geschrieben!",
      :endlich => "Finally.",
      :mama1 => "Anak? How are you? Did you arrive?",
      :ja_mama => "Yes, Ma.",
      :alles_gut => "Everything's fine.",
      :mama2 => "And the people? Are they nice?",
      :schritt => "Step by step",
      :toll => "Nice!",
      :musiker_her => "Lagos, Nigeria",
      :musiker_aus => "aus Nigeria",
      :tarek => "A little. Aber hier üben wir Deutsch, okay?",
      :jonas => "Mein Englisch ist okay. Aber mit Deutsch lernst du schneller. Deal?"
   },
   :tr => {
      :label => "Türkisch",
      :native => "Türkçe",
      :first => "Elif",
      :last => "Demir",
      :city => "Izmir",
      :land => "Türkei",
      :aus => "aus der Türkei",
      :inn => "in der Türkei",
      :staat => "türkisch",
      :pass_head => "Türkiye Cumhuriyeti - Pasaport",
      :uni => "Ege Üniversitesi, Izmir",
      :heimweh => "Ich vermisse Mamas Menemen. Und das Meer.",
      :buch => "ein Roman von Orhan Pamuk",
      :zeit => "In Izmir ist es jetzt eine Stunde später.",
      :name_ok => "richtig geschrieben!",
      :endlich => "Nihayet.",
      :mama1 => "Kızım, nasılsın? Vardın mı?",
      :ja_mama => "Evet, anne.",
      :alles_gut => "Her şey yolunda.",
      :mama2 => "İnsanlar nasıl? İyiler mi?",
      :schritt => "Adım adım",
      :toll => "Harika!",
      :musiker_her => "Ankara, Türkei",
      :musiker_aus => "aus der Türkei",
      :tarek => "Biraz! Ich bin in Neukölln aufgewachsen.",
      :jonas => "Ich kann nur »çok güzel«. Und »Döner mit alles«."
   },
   :uk => {
      :label => "Ukrainisch",
      :native => "Українська",
      :first => "Olena",
      :last => "Kowalenko",
      :city => "Lwiw",
      :land => "Ukraine",
      :aus => "aus der Ukraine",
      :inn => "in der Ukraine",
      :staat => "ukrainisch",
      :pass_head => "Ukraine - Pasport",
      :uni => "Medizinische Universität Lwiw",
      :heimweh => "Ich vermisse Mamas Borschtsch. Und Omas Garten.",
      :buch => "Gedichte von Taras Schewtschenko",
      :zeit => "In Lwiw ist es jetzt eine Stunde später.",
      :name_ok => "richtig geschrieben!",
      :endlich => "Нарешті.",
      :mama1 => "Доню, як ти? Ти доїхала?",
      :ja_mama => "Так, мамо.",
      :alles_gut => "Все добре.",
      :mama2 => "А люди? Вони привітні?",
      :schritt => "Крок за кроком",
      :toll => "Чудово!",
      :musiker_her => "Odesa, Ukraine",
      :musiker_aus => "aus der Ukraine",
      :tarek => "Leider nicht. Ich kann nur »Djakuju«. Das heißt danke, oder?",
      :jonas => "Ich kann nur »Djakuju«."
   },
  }
  WORD_TR = {
    :adresse => { :es => "dirección", :ar => "ﻥﺍﻮﻨﻋ", :fr => "adresse", :tr => "adres", :uk => "адреса" },
    :altpapier => { :es => "papel usado", :ar => "ﻞﻤﻌﺘﺴﻣ ﻕﺭﻭ", :fr => "vieux papiers", :tr => "atık kâğıt", :uk => "макулатура" },
    :anmelden => { :es => "empadronarse", :ar => "ﻦﻜﺴﻟﺍ ﻞﻴﺠﺴﺗ", :fr => "déclarer son domicile", :tr => "ikamet kaydı yaptırmak", :uk => "зареєструватися" },
    :aufbewahren => { :es => "guardar", :ar => "ﻆﻔﺘﺤﻳ", :fr => "conserver", :tr => "saklamak", :uk => "зберігати" },
    :ausdrucken => { :es => "imprimir", :ar => "ﻊﺒﻄﻳ", :fr => "imprimer", :tr => "yazdırmak", :uk => "роздрукувати" },
    :ausfuellen => { :es => "rellenar", :ar => "ﻸﻤﻳ", :fr => "remplir", :tr => "doldurmak", :uk => "заповнити" },
    :ausgang => { :es => "salida", :ar => "ﺝﺮﺨﻣ", :fr => "sortie", :tr => "çıkış", :uk => "вихід" },
    :baustelle => { :es => "obra", :ar => "ﺀﺎﻨﺑ ﻊﻗﻮﻣ", :fr => "chantier", :tr => "inşaat alanı", :uk => "будівництво" },
    :bescheinigung => { :es => "certificado", :ar => "ﺓﺩﺎﻬﺷ", :fr => "attestation", :tr => "belge", :uk => "довідка" },
    :bewerbung => { :es => "solicitud de empleo", :ar => "ﻒﻴﻇﻮﺗ ﺐﻠﻃ", :fr => "candidature", :tr => "iş başvurusu", :uk => "заявка на роботу" },
    :biomuell => { :es => "basura orgánica", :ar => "ﺔﻳﻮﻀﻋ ﺕﺎﻳﺎﻔﻧ", :fr => "déchets organiques", :tr => "organik atık", :uk => "органічні відходи" },
    :buergeramt => { :es => "oficina de atención ciudadana", :ar => "ﻦﻴﻨﻃﺍﻮﻤﻟﺍ ﺕﺎﻣﺪﺧ ﺐﺘﻜﻣ", :fr => "bureau des citoyens", :tr => "nüfus müdürlüğü", :uk => "бюро громадян" },
    :danke => { :es => "muchas gracias", :ar => "ﻼﻳﺰﺟ ﺍﺮﻜﺷ", :fr => "merci beaucoup", :tr => "çok teşekkürler", :uk => "дуже дякую" },
    :digga => { :es => "tío / colega", :ar => "ﻲﺒﺣﺎﺻ ﺎﻳ", :fr => "mec", :tr => "kanka", :uk => "братан" },
    :dom => { :es => "catedral", :ar => "ﺔﻴﺋﺍﺭﺪﺗﺎﻛ", :fr => "cathédrale", :tr => "katedral", :uk => "собор" },
    :duzen => { :es => "tutear / tratar de usted", :ar => "ﻚﺗﺮﻀﺣ / ﺖﻧﺃ", :fr => "tutoyer / vouvoyer", :tr => "sen / siz demek", :uk => "на «ти» / на «ви»" },
    :einzug => { :es => "fecha de mudanza", :ar => "ﻦﻜﺴﻟﺍ ﺦﻳﺭﺎﺗ", :fr => "date d'emménagement", :tr => "taşınma tarihi", :uk => "дата заселення" },
    :entschuldigung => { :es => "perdón / disculpe", :ar => "ﺍﻮﻔﻋ", :fr => "excusez-moi / pardon", :tr => "affedersiniz", :uk => "вибачте" },
    :entwerten => { :es => "validar el billete", :ar => "ﺓﺮﻛﺬﺘﻟﺍ ﻢﺘﺧ", :fr => "composter", :tr => "bileti onaylatmak", :uk => "компостувати" },
    :fahrkarte => { :es => "billete", :ar => "ﺓﺮﻛﺬﺗ", :fr => "billet / ticket", :tr => "bilet", :uk => "квиток" },
    :familienname => { :es => "apellido", :ar => "ﺔﻠﺋﺎﻌﻟﺍ ﻢﺳﺍ", :fr => "nom de famille", :tr => "soyadı", :uk => "прізвище" },
    :familienstand => { :es => "estado civil", :ar => "ﺔﻴﻋﺎﻤﺘﺟﻻﺍ ﺔﻟﺎﺤﻟﺍ", :fr => "situation familiale", :tr => "medeni durum", :uk => "сімейний стан" },
    :formular => { :es => "formulario", :ar => "ﺓﺭﺎﻤﺘﺳﺍ", :fr => "formulaire", :tr => "form", :uk => "бланк" },
    :geburtsdatum => { :es => "fecha de nacimiento", :ar => "ﺩﻼﻴﻤﻟﺍ ﺦﻳﺭﺎﺗ", :fr => "date de naissance", :tr => "doğum tarihi", :uk => "дата народження" },
    :gelbe_tonne => { :es => "contenedor amarillo", :ar => "ﺀﺍﺮﻔﺼﻟﺍ ﺔﻳﻭﺎﺤﻟﺍ", :fr => "poubelle jaune", :tr => "sarı çöp kutusu", :uk => "жовтий контейнер" },
    :geradeaus => { :es => "todo recto", :ar => "ﻡﺎﻣﻷﺍ ﻰﻟﺇ", :fr => "tout droit", :tr => "dümdüz", :uk => "прямо" },
    :gleis => { :es => "andén / vía", :ar => "ﺭﺎﻄﻘﻟﺍ ﻒﻴﺻﺭ", :fr => "voie / quai", :tr => "peron", :uk => "колія" },
    :halb_zehn => { :es => "las nueve y media", :ar => "ﻒﺼﻨﻟﺍﻭ ﺔﻌﺳﺎﺘﻟﺍ", :fr => "neuf heures et demie", :tr => "dokuz buçuk", :uk => "пів на десяту" },
    :hauptbahnhof => { :es => "estación central", :ar => "ﺔﻴﺴﻴﺋﺮﻟﺍ ﺔﻄﺤﻤﻟﺍ", :fr => "gare centrale", :tr => "ana tren istasyonu", :uk => "головний вокзал" },
    :hauptwohnung => { :es => "residencia principal", :ar => "ﻲﺴﻴﺋﺮﻟﺍ ﻦﻜﺴﻟﺍ", :fr => "résidence principale", :tr => "ana ikametgâh", :uk => "основне житло" },
    :hausnummer => { :es => "número de casa", :ar => "ﻝﺰﻨﻤﻟﺍ ﻢﻗﺭ", :fr => "numéro de maison", :tr => "kapı numarası", :uk => "номер будинку" },
    :integrationskurs => { :es => "curso de integración", :ar => "ﺝﺎﻣﺪﻧﻻﺍ ﺓﺭﻭﺩ", :fr => "cours d'intégration", :tr => "uyum kursu", :uk => "інтеграційний курс" },
    :klingel => { :es => "timbre", :ar => "ﺏﺎﺒﻟﺍ ﺱﺮﺟ", :fr => "sonnette", :tr => "zil", :uk => "дзвінок" },
    :kopie => { :es => "copia", :ar => "ﺔﺨﺴﻧ", :fr => "copie", :tr => "kopya", :uk => "копія" },
    :kurzstrecke => { :es => "billete de trayecto corto", :ar => "ﺓﺮﻴﺼﻗ ﺔﻓﺎﺴﻣ ﺓﺮﻛﺬﺗ", :fr => "ticket courte distance", :tr => "kısa mesafe bileti", :uk => "квиток на коротку відстань" },
    :langsamer => { :es => "más despacio", :ar => "ﺄﻄﺑﺃ", :fr => "plus lentement", :tr => "daha yavaş", :uk => "повільніше" },
    :ledig => { :es => "soltera / soltero", :ar => "ﺀﺎﺑﺰﻋ / ﺏﺰﻋﺃ", :fr => "célibataire", :tr => "bekâr", :uk => "неодружена" },
    :links => { :es => "a la izquierda", :ar => "ﺭﺎﺴﻳ", :fr => "à gauche", :tr => "sol", :uk => "ліворуч" },
    :meldebescheinigung => { :es => "certificado de empadronamiento", :ar => "ﻦﻜﺴﻟﺍ ﻞﻴﺠﺴﺗ ﺓﺩﺎﻬﺷ", :fr => "attestation de domicile", :tr => "ikamet belgesi", :uk => "довідка про реєстрацію" },
    :merkblatt => { :es => "hoja informativa", :ar => "ﺕﺎﻣﻮﻠﻌﻣ ﺓﺮﺸﻧ", :fr => "fiche d'information", :tr => "bilgi notu", :uk => "пам'ятка" },
    :mitbewohner => { :es => "compañero de piso", :ar => "ﻦﻜﺴﻟﺍ ﻚﻳﺮﺷ", :fr => "colocataire", :tr => "ev arkadaşı", :uk => "сусід по квартирі" },
    :morgen_gruss => { :es => "¡Buenos días!", :ar => "!ﺮﻴﺨﻟﺍ ﺡﺎﺒﺻ", :fr => "Bonjour !", :tr => "Günaydın!", :uk => "Доброго ранку!" },
    :pfand => { :es => "depósito de envases", :ar => "ﺕﺍﻮﺒﻌﻟﺍ ﻡﻮﺳﺭ", :fr => "consigne", :tr => "depozito", :uk => "застава за пляшку" },
    :pflichtfeld => { :es => "campo obligatorio", :ar => "ﻲﻣﺍﺰﻟﺇ ﻞﻘﺣ", :fr => "champ obligatoire", :tr => "zorunlu alan", :uk => "обов'язкове поле" },
    :putzplan => { :es => "turnos de limpieza", :ar => "ﻒﻴﻈﻨﺘﻟﺍ ﻝﻭﺪﺟ", :fr => "planning de ménage", :tr => "temizlik planı", :uk => "графік прибирання" },
    :rechts => { :es => "a la derecha", :ar => "ﻦﻴﻤﻳ", :fr => "à droite", :tr => "sağ", :uk => "праворуч" },
    :reisepass => { :es => "pasaporte", :ar => "ﺮﻔﺳ ﺯﺍﻮﺟ", :fr => "passeport", :tr => "pasaport", :uk => "закордонний паспорт" },
    :restmuell => { :es => "basura general", :ar => "ﺔﻣﺎﻋ ﺕﺎﻳﺎﻔﻧ", :fr => "ordures ménagères", :tr => "genel çöp", :uk => "змішані відходи" },
    :sachbearbeiterin => { :es => "funcionaria", :ar => "ﺔﺼﺘﺨﻤﻟﺍ ﺔﻔﻇﻮﻤﻟﺍ", :fr => "agente administrative", :tr => "görevli memur", :uk => "працівниця установи" },
    :schrippe => { :es => "panecillo", :ar => "ﺮﻴﻐﺻ ﺰﺒﺧ", :fr => "petit pain", :tr => "küçük ekmek", :uk => "булочка" },
    :staatsangehoerigkeit => { :es => "nacionalidad", :ar => "ﺔﻴﺴﻨﺠﻟﺍ", :fr => "nationalité", :tr => "uyruk", :uk => "громадянство" },
    :steuer_id => { :es => "número de identificación fiscal", :ar => "ﻲﺒﻳﺮﻀﻟﺍ ﻢﻗﺮﻟﺍ", :fr => "numéro fiscal", :tr => "vergi kimlik numarası", :uk => "податковий номер" },
    :strasse => { :es => "calle", :ar => "ﻉﺭﺎﺷ", :fr => "rue", :tr => "cadde / sokak", :uk => "вулиця" },
    :termin => { :es => "cita", :ar => "ﺪﻋﻮﻣ", :fr => "rendez-vous", :tr => "randevu", :uk => "запис на прийом" },
    :terminvereinbarung => { :es => "pedir cita", :ar => "ﺪﻋﻮﻣ ﺰﺠﺣ", :fr => "prise de rendez-vous", :tr => "randevu alma", :uk => "запис (бронювання)" },
    :umleitung => { :es => "desvío", :ar => "ﺔﻠﻳﻮﺤﺗ", :fr => "déviation", :tr => "sapma yolu", :uk => "об'їзд" },
    :umsteigen => { :es => "hacer transbordo", :ar => "ﺭﺎﻄﻘﻟﺍ ﺮﻴﻴﻐﺗ", :fr => "changer de train", :tr => "aktarma yapmak", :uk => "пересідати" },
    :unterlagen => { :es => "documentos", :ar => "ﺕﺍﺪﻨﺘﺴﻣ", :fr => "documents", :tr => "belgeler", :uk => "документи" },
    :unterschrift => { :es => "firma", :ar => "ﻊﻴﻗﻮﺗ", :fr => "signature", :tr => "imza", :uk => "підпис" },
    :vermieterin => { :es => "casera", :ar => "ﻦﻜﺴﻟﺍ ﺔﺒﺣﺎﺻ", :fr => "propriétaire", :tr => "ev sahibi", :uk => "орендодавиця" },
    :verspaetung => { :es => "retraso", :ar => "ﺮﻴﺧﺄﺗ", :fr => "retard", :tr => "gecikme", :uk => "запізнення" },
    :verstehe_nicht => { :es => "No lo entiendo.", :ar => ".ﻚﻟﺫ ﻢﻬﻓﺃ ﻻ", :fr => "Je ne comprends pas.", :tr => "Anlamıyorum.", :uk => "Я цього не розумію." },
    :vorstellungsgespraech => { :es => "entrevista de trabajo", :ar => "ﻞﻤﻋ ﺔﻠﺑﺎﻘﻣ", :fr => "entretien d'embauche", :tr => "iş görüşmesi", :uk => "співбесіда" },
    :wartenummer => { :es => "número de espera", :ar => "ﺭﺎﻈﺘﻧﻻﺍ ﻢﻗﺭ", :fr => "numéro d'attente", :tr => "sıra numarası", :uk => "номер у черзі" },
    :wat => { :es => "qué / eso (dialecto)", :ar => "(ﺔﺠﻬﻟ) ﺍﺫﺎﻣ", :fr => "quoi / ça (dialecte)", :tr => "ne / şu (şive)", :uk => "що / це (діалект)" },
    :wg => { :es => "piso compartido", :ar => "ﻙﺮﺘﺸﻣ ﻦﻜﺳ", :fr => "colocation", :tr => "paylaşımlı ev", :uk => "спільна квартира" },
    :wgb => { :es => "confirmación del arrendador", :ar => "ﻦﻜﺴﻟﺍ ﺐﺣﺎﺻ ﺪﻴﻛﺄﺗ", :fr => "attestation du logeur", :tr => "ev sahibi onayı", :uk => "підтвердження орендодавця" },
    :wiederholen => { :es => "repetir", :ar => "ﺭﺮﻜﻳ", :fr => "répéter", :tr => "tekrarlamak", :uk => "повторити" },
    :zu_fuss => { :es => "a pie", :ar => "ﻡﺍﺪﻗﻷﺍ ﻰﻠﻋ ﺍﺮﻴﺳ", :fr => "à pied", :tr => "yürüyerek", :uk => "пішки" },
  }
end
