"""Übersetzungen für die neuen Wörter des Ports (Reihenfolge: es, ar, fr, tr, uk).
Englisch steht direkt im Wörterbuch (Feld en).
Arabisch hier in normaler (logischer) Schreibweise – der Browser verbindet die Buchstaben selbst."""
TR = {
 # Einkauf & Küche (Präfix it_)
 "it_apfel": ["manzana", "تفاحة", "pomme", "elma", "яблуко"],
 "it_banane": ["plátano", "موزة", "banane", "muz", "банан"],
 "it_zitrone": ["limón", "ليمونة", "citron", "limon", "лимон"],
 "it_tomate": ["tomate", "طماطم", "tomate", "domates", "помідор"],
 "it_zwiebel": ["cebolla", "بصلة", "oignon", "soğan", "цибуля"],
 "it_knoblauch": ["ajo", "ثوم", "ail", "sarımsak", "часник"],
 "it_karotte": ["zanahoria", "جزرة", "carotte", "havuç", "морква"],
 "it_kartoffel": ["papa / patata", "بطاطا", "pomme de terre", "patates", "картопля"],
 "it_gurke": ["pepino", "خيار", "concombre", "salatalık", "огірок"],
 "it_milch": ["leche", "حليب", "lait", "süt", "молоко"],
 "it_kaese": ["queso", "جبن", "fromage", "peynir", "сир"],
 "it_butter": ["mantequilla", "زبدة", "beurre", "tereyağı", "масло"],
 "it_eier": ["huevos", "بيض", "œufs", "yumurta", "яйця"],
 "it_brot": ["pan", "خبز", "pain", "ekmek", "хліб"],
 "it_broetchen": ["panecillo", "خبز صغير", "petit pain", "küçük ekmek", "булочка"],
 "it_reis": ["arroz", "أرز", "riz", "pirinç", "рис"],
 "it_nudeln": ["pasta / fideos", "معكرونة", "pâtes", "makarna", "макарони"],
 "it_salz": ["sal", "ملح", "sel", "tuz", "сіль"],
 "it_kaffee": ["café", "قهوة", "café", "kahve", "кава"],
 "it_chips": ["papas fritas de bolsa", "رقائق البطاطس", "chips", "cips", "чипси"],
 "it_schokolade": ["chocolate", "شوكولاتة", "chocolat", "çikolata", "шоколад"],
 "it_wasser": ["agua", "ماء", "eau", "su", "вода"],
 "it_saft": ["jugo / zumo", "عصير", "jus", "meyve suyu", "сік"],
 "it_topf": ["olla", "قِدر", "casserole", "tencere", "каструля"],
 "it_pfanne": ["sartén", "مقلاة", "poêle", "tava", "сковорідка"],
 "it_messer": ["cuchillo", "سكين", "couteau", "bıçak", "ніж"],
 "it_loeffel": ["cuchara", "ملعقة", "cuillère", "kaşık", "ложка"],
 "it_teller": ["plato", "صحن", "assiette", "tabak", "тарілка"],
 "it_oel": ["aceite", "زيت", "huile", "yağ", "олія"],
 "it_pfeffer": ["pimienta", "فلفل أسود", "poivre", "karabiber", "перець"],
 # Episode 1
 "kochen": ["cocinar", "يطبخ", "cuisiner", "yemek pişirmek", "готувати"],
 "schneiden": ["cortar", "يقطع", "couper", "kesmek", "різати"],
 "salz": ["sal", "ملح", "sel", "tuz", "сіль"],
 "zwiebel": ["cebolla", "بصلة", "oignon", "soğan", "цибуля"],
 "messer": ["cuchillo", "سكين", "couteau", "bıçak", "ніж"],
 "topf": ["olla", "قِدر", "casserole", "tencere", "каструля"],
 "lecker": ["rico, delicioso", "لذيذ", "délicieux", "lezzetli", "смачний"],
 "buchstabieren": ["deletrear", "يتهجّى", "épeler", "hecelemek", "називати по буквах"],
 "spieleabend": ["noche de juegos", "سهرة ألعاب", "soirée jeux", "oyun gecesi", "вечір ігор"],
 "regel": ["regla", "قاعدة", "règle", "kural", "правило"],
 # Episode 3
 "einkaufszettel": ["lista de compras", "قائمة المشتريات", "liste de courses", "alışveriş listesi", "список покупок"],
 "kasse": ["caja", "صندوق الدفع", "caisse", "kasa", "каса"],
 "bar_zahlen": ["pagar en efectivo", "يدفع نقدًا", "payer en espèces", "nakit ödemek", "платити готівкою"],
 "bon": ["recibo", "إيصال", "ticket de caisse", "fiş", "чек"],
 "angebot": ["oferta", "عرض خاص", "promotion", "indirim", "акція"],
 "kuehlschrank": ["nevera", "ثلاجة", "frigo", "buzdolabı", "холодильник"],
 "einstufungstest": ["prueba de nivel", "اختبار تحديد المستوى", "test de niveau", "seviye tespit sınavı", "тест на рівень"],
 "kurs": ["curso", "دورة", "cours", "kurs", "курс"],
 "gegen_sechs": ["hacia las seis", "حوالي السادسة", "vers six heures", "altı sularında", "близько шостої"],
 "tor": ["gol", "هدف", "but", "gol", "гол"],
 "knapp": ["por poco", "بالكاد", "de justesse", "kıl payı", "ледь-ледь"],
 "umgangssprache": ["lenguaje coloquial", "اللغة العامية", "langue familière", "günlük dil", "розмовна мова"],
 "abschied": ["despedida", "وداع", "adieu", "veda", "прощання"],
 "vermissen": ["extrañar", "يشتاق إلى", "manquer à qqn", "özlemek", "сумувати за"],
 "schmecken": ["saber (a)", "يكون طعمه", "avoir du goût", "tadı olmak", "смакувати"],
 # Episode 4
 "lebenslauf": ["currículum", "سيرة ذاتية", "CV", "özgeçmiş", "резюме"],
 "schichtdienst": ["trabajo por turnos", "عمل بنظام المناوبات", "travail posté", "vardiyalı çalışma", "змінна робота"],
 "arbeitsvertrag": ["contrato de trabajo", "عقد عمل", "contrat de travail", "iş sözleşmesi", "трудовий договір"],
 "probezeit": ["periodo de prueba", "فترة التجربة", "période d'essai", "deneme süresi", "випробувальний термін"],
 "anzeige": ["anuncio de piso", "إعلان شقة", "annonce de logement", "ev ilanı", "оголошення про квартиру"],
 "kaltmiete": ["alquiler sin gastos", "الإيجار بدون تكاليف", "loyer hors charges", "çıplak kira", "оренда без комунальних"],
 "nebenkosten": ["gastos adicionales", "تكاليف إضافية", "charges", "yan giderler", "комунальні платежі"],
 "warmmiete": ["alquiler con gastos", "الإيجار مع التكاليف", "loyer charges comprises", "aidatlı kira", "оренда з комунальними"],
 "kaution": ["depósito / fianza", "تأمين / وديعة", "caution", "depozito", "застава"],
 "besichtigung": ["visita (del piso)", "معاينة", "visite", "ev gezme", "огляд квартири"],
 "schufa": ["informe de crédito", "تقرير الجدارة الائتمانية", "rapport de solvabilité", "kredi raporu", "кредитна довідка"],
 "mieter": ["inquilino/a", "مستأجر/ة", "locataire", "kiracı", "орендар"],
 "ummelden": ["cambiar el empadronamiento", "تسجيل عنوان جديد", "déclarer un changement d'adresse", "adres değişikliği bildirmek", "перереєструватися"],
 "konto": ["cuenta bancaria", "حساب مصرفي", "compte bancaire", "banka hesabı", "банківський рахунок"],
 "iban": ["IBAN", "رقم الحساب الدولي", "IBAN", "IBAN", "IBAN"],
 "ueberweisung": ["transferencia", "حوالة مصرفية", "virement", "havale", "банківський переказ"],
 "verwendungszweck": ["concepto (del pago)", "سبب الدفع", "motif du virement", "ödeme açıklaması", "призначення платежу"],
 "geldautomat": ["cajero automático", "صرّاف آلي", "distributeur", "ATM", "банкомат"],
 "pin": ["PIN", "الرقم السري", "code PIN", "PIN", "PIN-код"],
 "veedel": ["barrio (Colonia)", "حيّ (في كولونيا)", "quartier (Cologne)", "semt (Köln)", "район (Кельн)"],
 "hausordnung": ["reglamento de la casa", "نظام المبنى", "règlement intérieur", "bina kuralları", "правила будинку"],
 # Episode 5
 "uebergabe": ["traspaso de turno", "تسليم المناوبة", "transmission", "vardiya devri", "передача зміни"],
 "fieber": ["fiebre", "حُمّى", "fièvre", "ateş", "температура"],
 "blutdruck": ["presión arterial", "ضغط الدم", "tension artérielle", "tansiyon", "тиск"],
 "schmerzen": ["dolor", "ألم", "douleur", "ağrı", "біль"],
 "dienstplan": ["horario de turnos", "جدول المناوبات", "planning", "nöbet çizelgesi", "графік чергувань"],
 "fruehdienst": ["turno de mañana", "المناوبة الصباحية", "service du matin", "sabah vardiyası", "рання зміна"],
 "feierabend": ["fin de la jornada", "نهاية الدوام", "fin de journée", "mesai bitimi", "кінець робочого дня"],
 "kollegin": ["compañera de trabajo", "زميلة", "collègue", "iş arkadaşı", "колега"],
 "paket": ["paquete", "طرد", "colis", "paket", "посилка"],
 "benachrichtigung": ["aviso de entrega", "إشعار استلام", "avis de passage", "teslimat bildirimi", "повідомлення про доставку"],
 "fahrrad": ["bicicleta", "دراجة", "vélo", "bisiklet", "велосипед"],
 "leihen": ["prestar / alquilar", "يستعير / يستأجر", "emprunter / louer", "ödünç almak / kiralamak", "позичати / брати напрокат"],
 "koebes": ["camarero (Colonia)", "نادل (كولونيا)", "serveur (Cologne)", "garson (Köln)", "офіціант (Кельн)"],
 "halver_hahn": ["panecillo de centeno con queso", "خبز جاودار بالجبن", "petit pain au seigle et fromage", "peynirli çavdar ekmeği", "житня булочка з сиром"],
 "prost": ["¡salud!", "في صحتك!", "santé !", "şerefe!", "будьмо!"],
 # Episode 6
 "krankmelden": ["avisar que estás enfermo", "يبلّغ عن مرضه", "se déclarer malade", "hastalık bildirmek", "повідомити про хворобу"],
 "krankschreibung": ["baja médica", "إجازة مرضية", "arrêt maladie", "hastalık raporu", "лікарняний"],
 "gesundheitskarte": ["tarjeta sanitaria", "بطاقة التأمين الصحي", "carte d'assurance maladie", "sağlık kartı", "картка медичного страхування"],
 "krankenkasse": ["seguro de salud", "صندوق التأمين الصحي", "caisse d'assurance maladie", "sağlık sigortası", "лікарняна каса"],
 "passfoto": ["foto de pasaporte", "صورة جواز سفر", "photo d'identité", "vesikalık fotoğraf", "фото на паспорт"],
 "warteschleife": ["llamada en espera", "قائمة الانتظار الهاتفية", "file d'attente téléphonique", "telefonda bekleme", "очікування на лінії"],
 "wartezimmer": ["sala de espera", "غرفة الانتظار", "salle d'attente", "bekleme odası", "приймальня"],
 "halsschmerzen": ["dolor de garganta", "التهاب الحلق", "mal de gorge", "boğaz ağrısı", "біль у горлі"],
 "husten": ["tos", "سعال", "toux", "öksürük", "кашель"],
 "grippe": ["gripe", "إنفلونزا", "grippe", "grip", "грип"],
 "rezept": ["receta médica", "وصفة طبية", "ordonnance", "reçete", "рецепт"],
 "apotheke": ["farmacia", "صيدلية", "pharmacie", "eczane", "аптека"],
 "zuzahlung": ["copago", "مساهمة في الدفع", "participation", "katkı payı", "доплата"],
 "einnehmen": ["tomar (medicamentos)", "يتناول (الدواء)", "prendre (un médicament)", "(ilaç) almak", "приймати (ліки)"],
 "gute_besserung": ["¡que te mejores!", "سلامتك!", "bon rétablissement !", "geçmiş olsun!", "одужуй!"],
 # Episode 7
 "urlaub": ["vacaciones", "إجازة", "vacances", "tatil", "відпустка"],
 "deutschlandticket": ["billete Alemania", "تذكرة ألمانيا", "Deutschlandticket", "Almanya bileti", "квиток Deutschlandticket"],
 "zugbindung": ["billete para un tren concreto", "تذكرة مرتبطة بقطار محدد", "billet lié à un train", "trene bağlı bilet", "прив'язка до потяга"],
 "gleiswechsel": ["cambio de andén", "تغيير الرصيف", "changement de voie", "peron değişikliği", "зміна колії"],
 "anschluss": ["conexión / enlace", "قطار الربط", "correspondance", "aktarma bağlantısı", "пересадка"],
 "servus": ["¡hola! / ¡chao!", "مرحبًا / وداعًا", "salut !", "selam! / hoşça kal!", "привіт! / бувай!"],
 "semmel": ["panecillo (Baviera)", "خبز صغير (بافاريا)", "petit pain (Bavière)", "küçük ekmek (Bavyera)", "булочка (Баварія)"],
 "brezel": ["pretzel", "بريتزل", "bretzel", "brezel", "брецель"],
 "mass": ["litro de cerveza", "لتر بيرة", "litre de bière", "bir litre bira", "літр пива"],
 "postkarte": ["postal", "بطاقة بريدية", "carte postale", "kartpostal", "листівка"],
 "wiederaufbau": ["reconstrucción", "إعادة البناء", "reconstruction", "yeniden inşa", "відбудова"],
 "versoehnung": ["reconciliación", "مصالحة", "réconciliation", "barışma", "примирення"],
 "saechsisch": ["dialecto sajón", "اللهجة السكسونية", "dialecte saxon", "Saksonya lehçesi", "саксонський діалект"],
 # Episode 8
 "auslaenderbehoerde": ["oficina de extranjería", "دائرة الأجانب", "bureau des étrangers", "yabancılar dairesi", "відомство у справах іноземців"],
 "aufenthaltserlaubnis": ["permiso de residencia", "تصريح إقامة", "titre de séjour", "oturma izni", "дозвіл на проживання"],
 "frist": ["plazo", "مهلة", "délai", "son tarih", "термін"],
 "verlaengern": ["prolongar", "يمدّد", "prolonger", "uzatmak", "продовжити"],
 "antrag": ["solicitud", "طلب", "demande", "başvuru", "заява"],
 "checkliste": ["lista de control", "قائمة تحقق", "liste de contrôle", "kontrol listesi", "контрольний список"],
 "gehaltsabrechnung": ["nómina", "كشف راتب", "fiche de paie", "maaş bordrosu", "розрахунковий лист"],
 "sehr_geehrte": ["Estimados señores", "السادة المحترمون", "Madame, Monsieur", "Sayın ilgili", "Шановні пані та панове"],
 "nachreichen": ["presentar después", "يقدّم لاحقًا", "envoyer plus tard", "sonradan teslim etmek", "подати пізніше"],
 "fiktionsbescheinigung": ["certificado provisional de residencia", "شهادة إقامة مؤقتة", "attestation provisoire de séjour", "geçici oturum belgesi", "тимчасова довідка про перебування"],
 "aufenthaltstitel": ["título de residencia", "سند الإقامة", "titre de séjour", "oturum belgesi", "посвідка на проживання"],
 "mut": ["valor, coraje", "شجاعة", "courage", "cesaret", "сміливість"],
 # Episode 9
 "veedelsfest": ["fiesta del barrio", "مهرجان الحي", "fête de quartier", "mahalle şenliği", "свято району"],
 "behauptung": ["afirmación", "ادّعاء", "affirmation", "iddia", "твердження"],
 "verallgemeinerung": ["generalización", "تعميم", "généralisation", "genelleme", "узагальнення"],
 "vorurteil": ["prejuicio", "تحيّز / حكم مسبق", "préjugé", "önyargı", "упередження"],
 "herkunft": ["origen", "أصل", "origine", "köken", "походження"],
 "beurteilen": ["juzgar", "يحكم على", "juger", "yargılamak", "оцінювати"],
 "suendenbock": ["chivo expiatorio", "كبش فداء", "bouc émissaire", "günah keçisi", "цап-відбувайло"],
 "sachlich": ["objetivo, sereno", "موضوعي", "objectif, factuel", "nesnel", "по суті, об'єктивно"],
 "quelle": ["fuente", "مصدر", "source", "kaynak", "джерело"],
 "zivilcourage": ["valentía cívica", "شجاعة مدنية", "courage civique", "sivil cesaret", "громадянська мужність"],
 "ordnerin": ["encargada de seguridad", "منظِّمة / مسؤولة أمن", "agente d'accueil et de sécurité", "görevli (güvenlik)", "розпорядниця"],
 "notruf": ["número de emergencia 110", "رقم الطوارئ 110", "numéro d'urgence 110", "acil durum numarası 110", "екстрений виклик 110"],
 # Episode 10
 "moin": ["¡hola! (norte de Alemania)", "مرحبًا (شمال ألمانيا)", "salut ! (nord de l'Allemagne)", "merhaba! (Kuzey Almanya)", "привіт! (північ Німеччини)"],
 "fischbroetchen": ["bocadillo de pescado", "ساندويتش سمك", "sandwich au poisson", "balık ekmek", "булочка з рибою"],
 "sprachzertifikat": ["certificado de idioma", "شهادة لغة", "certificat de langue", "dil sertifikası", "мовний сертифікат"],
 "pruefung": ["examen", "امتحان", "examen", "sınav", "іспит"],
 "verschieben": ["aplazar", "يؤجّل", "reporter", "ertelemek", "перенести"],
 "bestanden": ["aprobado", "ناجح", "réussi", "geçti", "склала (іспит)"],
 "selbststaendig": ["independiente", "مستقل", "autonome", "bağımsız", "самостійно"],
 "zuhause": ["hogar", "بيت / وطن", "chez-soi", "yuva, ev", "дім"],
}
ORIGINS_EXTRA = {"es": {}, "ar": {}, "fr": {}, "en": {}, "tr": {}, "uk": {}}
